### ISSUE TITLE
Random stata stuff

### ISSUE THREAD

**Issue by amarchenko26** [amarchenko26/metoo#59]
Hi Maggie :) Just putting together some random stata fixes i'd love your help with when you have a chance. these are non-urgent, just spread them out according to whatever's convenient for you. I might add a few more things to this list as i remember them. 

- 
![image](https://github.com/user-attachments/assets/6337aef5-d820-4e3f-b894-881abdcb382c)
the duration table's (duration_corr.tex) outcome variable units are too small to be seen in a table. can you fix this? you can change the regression to logit or do something else clever 
-  fix years formatting in all summary / balance tables so it doesn't display as 2,014
- duration_by_file figure in /figures/ doesn't generate a file that's viewable on overleaf. When this figure is included in the overleaf file, the compilation breaks the document. does this happen with you too? 
- Make the summary table show summary values for the estimation sample. That is, the summary table and balance tables should have all the sample restrictions that we normally have for the .did analysis. So there shouldn't be dates in the 1970s etc.

**Comment by maggiejzl** [comment]
- Added more decimal places to the table
- Did not find a better way to fix year formatting besides going into the tex files on Overleaf and manually removing the commas
- Graph was being saved in the wrong format (gph); updated now
- Updated sample restrictions
