### ISSUE TITLE
Figure out state vs EEOC duplicates

### ISSUE THREAD

**Issue by amarchenko26** [amarchenko26/metoo#68]
Why would a person file in one but not the other? Are there differences (e.g. definition of SH)? Do we have duplicate cases, since state agencies can pass along to EEOC? 
- ---> TO DO - Look at outcome "removed to EEOC" and drop these cases if the case occurred between the time that we have EEOC data, aka YYY -- until January 2018.
- ---> Do we have to go back and ask states whether they gave us cases double-filed with EEOC? 
- ---> Do we have a data driven-way of solving this question?

**Comment by maggiejzl** [comment]
Added institutional differences section to OverLeaf and dropped removed cases
