### ISSUE TITLE
create admin closure outcome & multi category tag

### ISSUE THREAD

**Issue by amarchenko26** [amarchenko26/metoo#70]
- **Multi category cases:** Is it the agency or the complainant who decides what basis to tag the case as? (What category would a black woman who was sexually harassed select, race or sex based discrimination?) In courts, you might only record whichever discrimination is the most severe, so are we worried that what is driving the results is the kind of discrimination is selected...for example, in multi category cases, before metoo everybody chose Race but after everybody choose Sex because they think it'll be better for their outcomes. Does the number of multi-category cases go up after Metoo? If we are concerned that complainants are "cherry picking" the type of case type they choose to file, we can do a diff in diff similar to what we're already doing, but where the LHS variable is the share of cases that have multiple tags (e.g. sex discrimination and race based discrimination) -- MAGGIE. 
- Create a new outcome variable that is capturing whether the case was administratively closed. We want to have a proxy for how many cases were thrown out for "bogus" reasons....create a variable that = 1 if case was administratively or procedurally closed. i.e., they couldn't find respondent, couldn't find complainant, failure to cooperate, administrative dismissal, CP failed to respond, etc

**Comment by maggiejzl** [comment]
- Created tags for admin_close and multi_cat
- States with single basis: IL, MA, MN (case can have multiple bases but each row is a separate allegation)
- States with multiple bases: AK, HI, MI, WA, TX, ND
